INSERT INTO rounddetail
           (round_id,
            delta1,
            delta2,
            delta3,
            delta4,
            winner_id,
            hua_count,
            hand_id,
            lezi,
            menqing,
            zimo,
            dianpao_id,
            qianggang,
            huangfan,
            gangkai,
            laoyue,
            chengbao_id,
            created) 
VALUES     (@round_id,
            @delta1,
            @delta2,
            @delta3,
            @delta4,
            @winner_id,
            @hua_count,
            @hand_id,
            @lezi,
            @menqing,
            @zimo,
            @dianpao_id,
            @qianggang,
            @huangfan,
            @gangkai,
            @laoyue,
            @chengbao_id,
            datetime('now','localtime'));
--SELECT CAST(SCOPE_IDENTITY() AS INT);